[tool.poetry]
name = "pybitblock"
version = "2.0.12"
description = "Python Bitcoin block dashboard, transactions, send message to Space and more"
license="MIT"
authors = ["curly60e <curly60e@piserver.xyz>", "SatoshiNakamotoBitcoin"]
readme="README.md"
repository="https://github.com/curly60e/pyblock"
homepage="https://github.com/curly60e/pyblock"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
art = "^5.3"
qrcode = "^7.3.1"
requests = "^2.26.0"
psutil = "^5.8.0"
simplejson = "^3.17.6"
certifi = "^2021.10.8"
chardet = "^4.0.0"
idna = "^3.3"
python-gnupg = "^0.4.7"
sseclient-py = "^1.7.2"
urllib3 = "^1.26.7"
lnpay-py = "^0.1.0"
xmltodict = "^0.12.0"
python-cfonts = "^1.5.2"
termcolor = "^1.1.0"
pycoingecko = "^2.2.0"
protobuf = "3.18.3"
six = "1.15.0"
robohash = "^1.1"
Pillow = ">=8.4,<10.0"
numpy = "^1.23.0"
googleapis-common-protos = "1.52.0"
pdfminer = "^20191125"
typer = "^0.4.0"
jq = "1.2.2"
html2text = "2020.1.16"
pdf2text = "1.0.0"
pdf2txt = "0.7.3"



[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pyblock = "pybitblock.console:main"
